name: Vettingo Evaluation Service CI
on:
  push:
    branches:
      - master
    path:
      - src/EvaluationService/**
      - tests/Vettingo.EvaluatonService.Tests/**
  pull_request:
    branches:
      - master
    path:
      - src/EvaluationService/**
      - tests/Vettingo.EvaluationService.Tests/**
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('src/AuthService/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore Dotnet Project
        run: dotnet restore src/EvaluationService/**/*.csproj
      - name: Build Dotnet Project
        run: dotnet build src/EvaluationService/Vettingo.EvaluationService.API --configuration Release
      - name: Test Dotnet Project
        run: dotnet test tests/Vettingo.EvaluationService.Tests --configuration release --verbosity normal --no-build --logger "trx;LogFileName=test_results.trx" --collect:"XPlat Code Coverage" 
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          path: ./tests/Vettingo.EvaluationService.Tests/TestResults/
          name: Test Results
      - name: upload code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-results
          path: ./tests/Vettingo.EvaluationService.Tests/TestResults/**/coverage.cobertura.xml
          retention-days: 30




       
    