name: Vettingo Notification Service CI
on:
  push:
    branches:
      - master
    paths:
      - 'src/NotificationService/**'
      - 'tests/Vettingo.NotificationService.Tests/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/NotificationService/**'
      - 'tests/Vettingo.NotificationService.Tests/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('src/NotificationService/**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Restore dependencies
        run: |
          dotnet restore src/NotificationService/**/*.csproj
      - name: Build
        run: |
          dotnet build src/NotificationService/Vettingo.NotificationService.API --configuration Release
      - name: Run tests
        run: |
          dotnet test tests/Vettingo.NotificationService.Tests --configuration Release --verbosity normal --no-build --logger "trx;LogFileName=test_results.trx" --collect:"XPlat Code Coverage"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          path: ./tests/Vettingo.NotificationService.Tests/TestResults/
          name: test-results    
          retention-days: 30
      - name: Upload code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-results
          path: ./tests/Vettingo.NotificationService.Tests/TestResults/**/coverage.cobertura.xml
          retention-days: 30
