<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.8" />

    <Compile Update="Entities\JobPosting.cs" />
    <Compile Update="Enums\EmploymentType.cs" />
    <Compile Update="Enums\ExperienceLevel.cs" />
    <Compile Update="Enums\JobPostingStatus.cs" />
    <Compile Update="Enums\WorkingModel.cs" />
  </ItemGroup>

</Project>
