<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP" Version="10.0.2" />
    <PackageReference Include="DotNetCore.CAP.PostgreSql" Version="10.0.2" />
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vettingo.SubscriptionService.Application\Vettingo.SubscriptionService.Application.csproj" />
    <ProjectReference Include="..\Vettingo.SubscriptionService.Domain\Vettingo.SubscriptionService.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
